---
#
# Ansible managed
#
repository:
  description: Install and configure collectd on your system.
  homepage: https://buluma.github.io/
  topics: collectd, ansible, molecule, tox, playbook, hacktoberfest
